language: node_js
node_js:
  - "0.12.5"
before_install:
  - "curl -L http://git.io/3l-rRa | /bin/sh"
services:
  - mongodb
env:
  - MONGO_URL="mongodb://heroku_zg5hr70q:30301l17uugma07sjvd9vhkeik@ds051843.mongolab.com:51843/heroku_zg5hr70q"
